spring:
  config.activate.on-profile: default
  datasource:
    #url: jdbc:mysql://localhost:3306/auto_readme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    url: jdbc:mysql://cloud-db.czymyzxo0gbq.ap-northeast-2.rds.amazonaws.com:3306/auto_readme?serverTimezone=Asia/Seoul&characterEncoding=UTF-8
    #username: root
    username: admin
    password: password!23
    driver-class-name: com.mysql.cj.jdbc.Driver
    hikari:
      maximum-pool-size: 5

  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        show_sql: true
        format_sql: true

openai:
  api-key: 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

chatgpt:
  api-key: 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
